version: '3.8'

services:
  postgres:
    container_name: node_test_db
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: node_test
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: node_test_redis
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
